### Importando as bibliotecas que serão utilizadas

In [1]:
import pandas as pd
import numpy as np

### Criando um DataFrame a paritr do CSV

In [2]:
# Como o separador usado no arquivo não é o padrão que é a vírgula, se fez necessário usar o parâmetro SET
df_varejo = pd.read_csv("base_varejo.csv", sep=";", encoding="utf-8")

### Verificando as primeiras linhas do DataFrame

In [3]:
df_varejo.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

### Mantendo apenas as colunas que não estão em branco

In [4]:
df_varejo = df_varejo.dropna(axis=1)
df_varejo

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO
...,...,...,...,...,...,...,...,...,...,...
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO

### Ajustando o nome das colunas para uma melhor identificá-las

In [6]:
df_varejo.columns = ["Data", "nota_fiscal", "id_cliente", "sexo", "estado_civil", "qtd_filhos", "classe_social", "sku_produto", "categoria_produto", "nome_produto"]
df_varejo

,Data,nota_fiscal,id_cliente,sexo,estado_civil,qtd_filhos,classe_social,sku_produto,categoria_produto,nome_produto
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO
...,...,...,...,...,...,...,...,...,...,...
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO