### Importando as bibliotecas que serão utilizadas

In [1]:
import pandas as pd
import numpy as np

### Criando um DataFrame a paritr do CSV

In [2]:
# Como o separador usado no arquivo não é o padrão que é a vírgula, se fez necessário usar o parâmetro SET
df_varejo = pd.read_csv("base_varejo.csv", sep=";", encoding="utf-8")

### Verificando as primeiras linhas do DataFrame

In [3]:
df_varejo.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

### Mantendo apenas as colunas que não estão em branco

In [4]:
df_varejo = df_varejo.dropna(axis=1)
df_varejo

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO
...,...,...,...,...,...,...,...,...,...,...
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO

### Ajustando o nome das colunas para uma melhor identificá-las

In [5]:
df_varejo.columns = ["Data", "nota_fiscal", "id_cliente", "sexo", "estado_civil", "qtd_filhos", "classe_social", "sku_produto", "categoria_produto", "nome_produto"]
df_varejo

,Data,nota_fiscal,id_cliente,sexo,estado_civil,qtd_filhos,classe_social,sku_produto,categoria_produto,nome_produto
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO
...,...,...,...,...,...,...,...,...,...,...
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO

### Verificando se há valores ausentes

In [18]:
df_varejo.isna().sum()

Data                 0
nota_fiscal          0
id_cliente           0
sexo                 0
estado_civil         0
qtd_filhos           0
classe_social        0
sku_produto          0
categoria_produto    0
nome_produto         0
Ano_venda            0
dtype: int64

### Convertendo a coluna Data para o formato Datetime

In [7]:
df_varejo["Data"] = pd.to_datetime(
    df_varejo["Data"],
    dayfirst=True
)

df_varejo

,Data,nota_fiscal,id_cliente,sexo,estado_civil,qtd_filhos,classe_social,sku_produto,categoria_produto,nome_produto
0,2019-02-01,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,2019-02-01,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,2019-02-01,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,2019-02-01,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO
...,...,...,...,...,...,...,...,...,...,...
829995,2022-08-19,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP
829996,2022-08-19,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA
829997,2022-08-19,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ
829998,2022-08-19,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA
829999,2022-08-19,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO

### Incluindo uma coluna de ano, para permitir análise anual

In [8]:
df_varejo["Ano_venda"] = df_varejo["Data"].dt.year
df_varejo

,Data,nota_fiscal,id_cliente,sexo,estado_civil,qtd_filhos,classe_social,sku_produto,categoria_produto,nome_produto,Ano_venda
0,2019-02-01,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,2019
1,2019-02-01,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,2019
2,2019-02-01,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,2019
3,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,2019
4,2019-02-01,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,2019
...,...,...,...,...,...,...,...,...,...,...,...
829995,2022-08-19,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,2022
829996,2022-08-19,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,2022
829997,2022-08-19,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,2022
829998,2022-08-19,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,2022
829999,2022-08-19,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,2022

### Ajustando os valores da coluna estado civil, tirando o número e colocando o status correspondente a cada número

In [9]:
def situacao(num):
    if num == 1:
        return "Casado"
    elif num == 2:
        return "Divorciado"
    elif num == 3:
        return "Separado"
    elif num == 4:
        return "Solteiro"
    elif num == 5:
        return "Viúvo"
    else:
        return "Verificar status"

df_varejo["estado_civil"] = df_varejo["estado_civil"].apply(situacao)
df_varejo

,Data,nota_fiscal,id_cliente,sexo,estado_civil,qtd_filhos,classe_social,sku_produto,categoria_produto,nome_produto,Ano_venda
0,2019-02-01,1000,534,M,Solteiro,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,2019
1,2019-02-01,1000,534,M,Solteiro,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,2019
2,2019-02-01,1000,534,M,Solteiro,1,C,178,HIGIENE,LENCO UMEDECIDO,2019
3,2019-02-01,1000,534,M,Solteiro,1,C,4,ALIMENTOS,ABACAXI,2019
4,2019-02-01,1000,534,M,Solteiro,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,2019
...,...,...,...,...,...,...,...,...,...,...,...
829995,2022-08-19,919822,155,F,Divorciado,0,B,183,ALIMENTOS,KETCHUP,2022
829996,2022-08-19,919822,155,F,Divorciado,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,2022
829997,2022-08-19,919822,155,F,Divorciado,0,B,227,ALIMENTOS,ARROZ,2022
829998,2022-08-19,919822,155,F,Divorciado,0,B,214,ALIMENTOS,CEBOLA,2022
829999,2022-08-19,919822,155,F,Divorciado,0,B,59,ALIMENTOS,SALGADINHO,2022

### Analisando estatisticamente a coluna de quantidade de filhos

In [10]:
df_varejo["qtd_filhos"].describe()

count    830000.00000
mean          1.14654
std           1.41696
min           0.00000
25%           0.00000
50%           0.00000
75%           2.00000
max           4.00000
Name: qtd_filhos, dtype: float64

### Calculando a média da quantidade de filhos por classe social

In [11]:
df_varejo.groupby("classe_social")["qtd_filhos"].mean()

classe_social
A    1.038931
B    1.146991
C    1.176914
Name: qtd_filhos, dtype: float64

### Verificando a quantidade de produtos por categoria

In [20]:
df_varejo.groupby("categoria_produto")["nome_produto"].count()

categoria_produto
#N/D            3650
ACESSORIOS     14557
ALIMENTOS     434767
BEBIDAS        43299
HIGIENE       155574
LIMPEZA       145754
PET            32399
Name: nome_produto, dtype: int64

### Verificando com estado civil realiza mais compras

In [24]:
df_varejo.groupby("estado_civil")["nota_fiscal"].count()

estado_civil
Casado        194873
Divorciado    194990
Separado      213742
Solteiro      202618
Viúvo          23777
Name: nota_fiscal, dtype: int64

### Verificando qual sexo compra mais

In [25]:
df_varejo.groupby("sexo")["nota_fiscal"].count()

sexo
F    432576
M    397424
Name: nota_fiscal, dtype: int64

### Verificando qual categoria de produto mais vende

In [26]:
df_varejo.groupby("categoria_produto")["nota_fiscal"].count()

categoria_produto
ACESSORIOS        14557
ALIMENTOS        434767
BEBIDAS           43299
HIGIENE          155574
LIMPEZA          145754
Não informado      3650
PET               32399
Name: nota_fiscal, dtype: int64

### Colocando "Não informado" na categoria que não tem nome

In [23]:
df_varejo["categoria_produto"] = df_varejo["categoria_produto"].replace(
    "#N/D",
    "NÃO INFORMADO"
)

df_varejo.groupby("categoria_produto")["nome_produto"].count()

categoria_produto
ACESSORIOS        14557
ALIMENTOS        434767
BEBIDAS           43299
HIGIENE          155574
LIMPEZA          145754
Não informado      3650
PET               32399
Name: nome_produto, dtype: int64